Reddit_client_id = 'Reddit client id here'
Reddit_client_secret = 'Reddit client secret here'
Reddit_username = 'Reddit username here'
Reddit_password = 'Reddit password here'
Reddit_user_agent = 'Reddit user agent here'
mysql_user = 'mysql userID here'
mysql_password = 'mysql password here'
mysql_database = 'mysql database name here'
Imgur_ClientID = 'Imgur ClientID here'
default_range = 'day'  # (day/week/month/year/all)
default_setting_type = 'hot'  # (hot/top/new/raising/controversial)
defaultlimit = 13
subreddit_list = ["list", "of", "subreddit", "names", "here"]
download_path = 'enter download path here'
logs_path = 'enter paths for logs here'
